name: Update Blog Links

on:
  push:
    branches:
      - main

jobs:
  update-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Blog Links
        run: |


      - name: Commit and Push Changes
        uses: divyanshutiwari09/blog-post-workflow@master
        with:
            max_post_count: 10
            feed_list: "https://www.huffpost.com/"
        
